import { Task } from "@prisma/client";
import Head from "next/head";
import Link from "next/link";
import { useState, useEffect } from "react";
import TaskModal from "~/components/TaskModal";
import {HiX} from "react-icons/hi";

import { api } from "~/utils/api";

export default function Home() {

  const [task, setTask] = useState<Task[]>([]);
  const [modalOpen, setModalOpen] = useState<boolean>(false);

  const { data: tasksData, isLoading } = api.task.getAll.useQuery({
    onSuccess(data){
      setTask(data)
    }
  });

  const { mutate: deleteTask} = api.task.delete.useMutation({
    onSuccess(data){
      setTask((prev) => prev.filter((item) => item.id !== data.id))
    }
  });

  if(!tasksData || isLoading) return <p>Loading...</p>

  return (
    <>
      <Head>
        <title>To do list</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     {modalOpen && <TaskModal setModalOpen={setModalOpen} setTask={setTask}/>}

      <main className="mx-auto my-12 max-x-3xl">
        <div className="flex justify-between">
          <h2 className="text-2xl font-semibold">My to-do list</h2>
          <button type="button" onClick={() => setModalOpen(true)} className="bg-violet-500 transition hover:bg-violet-600 text-sm p-2 rounded-md text-white">Add task</button>
        </div>

        <ul className="mt-4">
          {tasksData.map((item) => {
            const {id, title} = item
            return (
              <li key={id} className="flex justify-between items-center">
                <span>{title}</span>
                <HiX onClick={() => deleteTask({id})} className='cursor-pointer text-lg text-red-500' />
              </li>)}
          )}
        </ul>
      </main>
    </>
  );
}
